# Generated by Django 4.2.4 on 2023-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registered_lab_name', models.CharField(max_length=50)),
                ('Patient_name', models.CharField(max_length=50)),
                ('Patient_emailid', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=10)),
                ('Test_name', models.CharField(max_length=50)),
                ('Patient_dob', models.IntegerField()),
                ('Aadharno', models.IntegerField(max_length=12)),
            ],
        ),
    ]
