# Generated by Django 4.2.4 on 2023-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Aadharno',
            field=models.IntegerField(),
        ),
    ]
