# Generated by Django 4.2.4 on 2023-08-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=50)),
                ('lab_emailid', models.CharField(max_length=50)),
                ('lab_mobno', models.IntegerField(max_length=10)),
                ('user_password', models.CharField(max_length=10)),
            ],
        ),
    ]
